import type { HostEventDetail, HostEventSummary } from '@matemyparty/contracts';

export const hostEventDetail: HostEventDetail = {
  identifier: 'raymundo-6',
  publicSlug: 'raymundo-6',
  publicCode: 'SQ52LQE9',
  title: 'Raymundo’s 6th Birthday',
  celebrantName: 'Raymundo',
  celebrantAge: 6,
  startsAt: '2026-08-06T18:00:00.000Z',
  venueName: 'Kids Empire Dallas Hillcrest',
  status: 'DRAFT',
  templateKey: 'kids-night-dragon',
  primaryHostname: 'raymundo6th.domoforge.com',
  thumbnailImageRef: null,
  formattedAddress: null,
  readiness: {
    locationComplete: false,
    scheduleComplete: true,
    thumbnailConfigured: false,
  },
  statistics: {
    guestCount: 12,
    invitationCount: 8,
    openedCount: 5,
    rsvp: {
      pending: 3,
      accepted: 3,
      declined: 1,
      notSure: 1,
      cancelled: 0,
      confirmedTotal: 7,
      confirmedAdults: 4,
      confirmedChildren: 3,
      invitationsWithoutResponse: 3,
    },
  },
  eventType: 'KIDS_BIRTHDAY',
  endsAt: null,
  timezone: 'America/Chicago',
  defaultLocale: 'en-US',
  addressLine1: null,
  addressLine2: null,
  city: null,
  region: null,
  postalCode: null,
  countryCode: null,
  latitude: null,
  longitude: null,
  mapsUrl: null,
  publicThumbnailRef: null,
  rsvpDeadline: null,
  staticBackgroundRef: null,
  localizedContent: {
    'en-US': {
      title: 'Raymundo’s 6th Birthday',
      celebrantName: 'Raymundo',
      venueName: 'Kids Empire Dallas Hillcrest',
      hostMessage: null,
      arrivalInstructions: null,
      parkingInstructions: null,
      thumbnailAltText: 'Raymundo’s 6th birthday',
    },
    'es-MX': {
      title: 'Sexto cumpleaños de Raymundo',
      celebrantName: 'Raymundo',
      venueName: 'Kids Empire Dallas Hillcrest',
      hostMessage: null,
      arrivalInstructions: null,
      parkingInstructions: null,
      thumbnailAltText: 'Sexto cumpleaños de Raymundo',
    },
  },
  template: {
    key: 'kids-night-dragon',
    version: 1,
    animationMode: 'IMMERSIVE',
    videoBackgroundRef: '/private-media/raymundo-6/dragons-intro.mp4',
    staticFallbackRef: null,
    audioRef: '/private-media/raymundo-6/dragons-theme.mp3',
    animationEnabled: true,
    audioEnabled: true,
    overlayIntensity: 50,
  },
  revisionNumber: 1,
};

export const hostEventSummary: HostEventSummary = hostEventDetail;
